[intro_music]
audio_normalize_target = "-25"

[intro]
audio_normalize_target = "-40"

[outro_music]
audio_normalize_target = "-25"

[outro]
audio_normalize_target = "-25"

[shrine_clean]
audio_normalize_target = "-35"

[boss]
audio_normalize_target = "-26"

# Runner specific (for different mic audio)
[pfive_mic]
audio_normalize_target = "-21"
