[iTNTPiston]
display_name = "iTNTPiston"
src = "https://www.speedrun.com/user/iTNTPiston"
twitch = "https://twitch.tv/itntpiston"
youtube = "https://www.youtube.com/channel/UCjfDAsxdvo_cux_iMGk4-yw"
twitter = "https://www.twitter.com/i_piston"
bilibili = "https://space.bilibili.com/11564782"

